[package]
name = "confenc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
confenc_macros = { path = "./macros" }
confenc_crydec = { path = "./crydec" }